version: "2"

run:
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  disable:
    - copyloopvar
    - cyclop
    - depguard
    - exhaustruct
    - funlen
    - gocognit
    - goconst
    - intrange
    - paralleltest
    - testpackage
    - varnamelen
    - wrapcheck
